/**
 * Response shapes, for documentation only.
 *
 * These classes exist because Swagger builds its schemas from runtime metadata,
 * and a TypeScript `interface` leaves none — AuthResult and MeResponse would
 * both document as an empty object.
 *
 * Each one `implements` the interface the handler actually returns. That is the
 * whole point: it costs nothing at runtime (no handler constructs these) but it
 * makes the compiler reject documentation that has drifted from the real
 * response. Add a field to MeResponse without adding it here and the build
 * fails, which is the opposite of how API docs usually rot.
 */
import { ApiProperty } from '@nestjs/swagger';
import type { AuthResult } from '../auth.service';
import type { MeResponse } from '../me.service';
import type { ManagerListRow, MemberRow, TeamListRow } from '../directory.service';
import type { UserRole } from '../../db/tenant-context';

const UUID_EXAMPLE = '3f1c8a4e-9b2d-4c7a-8e15-2d6b0f9a1c33';

// `implements` needs a name, not an indexed access — AuthResult['user'] there is
// a TS2500. The alias is only to give that shape one.
type AuthResultUser = AuthResult['user'];

class AuthUserDto implements AuthResultUser {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  orgId!: string;

  @ApiProperty({ enum: ['owner', 'manager', 'member'], example: 'owner' })
  role!: UserRole;

  @ApiProperty({ example: 'Ada Owner' })
  name!: string;

  @ApiProperty({ format: 'email', example: 'ada@acme.test' })
  email!: string;
}

export class AuthResultDto implements AuthResult {
  @ApiProperty({
    description:
      'Bearer token for the Authorization header. Paste it into "Authorize" ' +
      'at the top of this page to call the protected endpoints.',
    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
  })
  accessToken!: string;

  @ApiProperty({
    description:
      'Opaque refresh token. Exchange it at POST /api/auth/refresh for a new ' +
      'access token before this one expires; each refresh returns a new refresh ' +
      'token and invalidates the one just used. Store it as securely as the ' +
      'session itself — see the AuthResult docs for why it is in the body and ' +
      'not a cookie.',
    example: 'yZ3k9Qm2...redacted',
  })
  refreshToken!: string;

  @ApiProperty({ type: AuthUserDto })
  user!: AuthUserDto;
}

export class MeResponseDto implements MeResponse {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  orgId!: string;

  @ApiProperty({ example: 'Acme Industries' })
  organizationName!: string;

  @ApiProperty({ enum: ['owner', 'manager', 'member'], example: 'owner' })
  role!: UserRole;

  @ApiProperty({ example: 'Ada Owner' })
  name!: string;

  @ApiProperty({ format: 'email', example: 'ada@acme.test' })
  email!: string;

  @ApiProperty({
    type: String,
    format: 'uuid',
    nullable: true,
    description:
      'The tenant key. NULL for an Owner, their own id for a Manager, their ' +
      "Manager's id for a Member (CLAUDE.md §1).",
    example: null,
  })
  managerId!: string | null;

  @ApiProperty({ type: String, format: 'uuid', nullable: true, example: null })
  teamId!: string | null;

  @ApiProperty({ type: String, nullable: true, example: null })
  roleTitle!: string | null;

  @ApiProperty({ type: Number, nullable: true, example: null })
  workflowStep!: number | null;

  @ApiProperty({ minimum: 0, maximum: 100, example: 50 })
  ranking!: number;

  @ApiProperty({ example: false })
  isReporter!: boolean;
}

/**
 * What createManager returns. The passcode is deliberately not here — it went to
 * the mailer, and that is the only place it exists in plaintext.
 */
export class ManagerProvisionedDto {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ example: 'Morgan Manager' })
  name!: string;

  @ApiProperty({ format: 'email', example: 'morgan@acme.test' })
  email!: string;

  @ApiProperty({ enum: ['manager'], example: 'manager' })
  role!: 'manager';

  @ApiProperty({ enum: ['active'], example: 'active' })
  status!: 'active';

  @ApiProperty({
    format: 'date-time',
    description: 'When the passcode expires. CLAUDE.md §1 specifies ~72h.',
    example: '2026-08-08T12:34:56.789Z',
  })
  passcodeExpiresAt!: Date;

  @ApiProperty({
    description:
      'Whether the invite email was sent. false means the account was still ' +
      'created and the passcode can be regenerated by the Owner.',
    example: true,
  })
  inviteEmailSent!: boolean;
}

/**
 * What createMember returns. Same shape as ManagerProvisionedDto plus the team
 * the member joined — and, identically, the passcode is deliberately absent: it
 * went to the mailer, the only place it exists in plaintext.
 */
export class MemberProvisionedDto {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ example: 'Sam Member' })
  name!: string;

  @ApiProperty({ format: 'email', example: 'sam@acme.test' })
  email!: string;

  @ApiProperty({ enum: ['member'], example: 'member' })
  role!: 'member';

  @ApiProperty({ enum: ['active'], example: 'active' })
  status!: 'active';

  @ApiProperty({
    format: 'uuid',
    description: "The team the member was added to — their manager's active team.",
    example: UUID_EXAMPLE,
  })
  teamId!: string;

  @ApiProperty({
    format: 'date-time',
    description: 'When the passcode expires. CLAUDE.md §1 specifies ~72h.',
    example: '2026-08-08T12:34:56.789Z',
  })
  passcodeExpiresAt!: Date;

  @ApiProperty({
    description:
      'Whether the invite email was sent. false means the account was still ' +
      'created and the passcode can be regenerated by the issuer.',
    example: true,
  })
  inviteEmailSent!: boolean;
}

/**
 * What createTeam returns. No passcode, no secret — a team is not a credential;
 * this is the safe, complete view of the row just created.
 */
export class TeamCreatedDto {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ example: 'Delivery Squad' })
  name!: string;

  @ApiProperty({
    format: 'uuid',
    description: 'The manager who owns this team.',
    example: UUID_EXAMPLE,
  })
  managerId!: string;

  @ApiProperty({ enum: ['active'], example: 'active' })
  status!: 'active';
}

/**
 * What regeneratePasscode returns. Like the provisioning DTOs, the passcode
 * itself is deliberately absent — it went to the mailer, the only place it exists
 * in plaintext. Role-neutral: the same route re-issues an invite for a manager or
 * a member, so `role` reports which one the target was.
 */
export class PasscodeRegeneratedDto {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ example: 'Morgan Manager' })
  name!: string;

  @ApiProperty({ format: 'email', example: 'morgan@acme.test' })
  email!: string;

  @ApiProperty({ enum: ['manager', 'member'], example: 'member' })
  role!: 'manager' | 'member';

  @ApiProperty({
    format: 'date-time',
    description: 'When the newly-issued passcode expires. CLAUDE.md §1 specifies ~72h.',
    example: '2026-08-08T12:34:56.789Z',
  })
  passcodeExpiresAt!: Date;

  @ApiProperty({
    description:
      'Whether the fresh invite email was sent. false means the passcode was ' +
      'still regenerated and can be regenerated again.',
    example: true,
  })
  inviteEmailSent!: boolean;
}

/**
 * One row of GET /api/auth/teams. `implements TeamListRow` so a field renamed in
 * the service is a compile error here, not silent doc drift. The two counts are
 * numbers (the service already `Number()`-ed the bigint the driver returns as a
 * string), and `memberCount` deliberately excludes the manager — see the service
 * SQL note.
 */
export class TeamListRowDto implements TeamListRow {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ example: 'Delivery Squad' })
  name!: string;

  @ApiProperty({
    format: 'uuid',
    description: 'The manager who owns this team.',
    example: UUID_EXAMPLE,
  })
  managerId!: string;

  @ApiProperty({ example: 'Morgan Manager' })
  managerName!: string;

  @ApiProperty({ format: 'email', example: 'morgan@acme.test' })
  managerEmail!: string;

  @ApiProperty({
    description: 'Active members on the team, not counting the manager.',
    example: 4,
  })
  memberCount!: number;

  @ApiProperty({
    description: 'Active members whose invite is not yet activated (no password set).',
    example: 1,
  })
  pendingInviteCount!: number;

  @ApiProperty({ format: 'date-time', example: '2026-08-08T12:34:56.789Z' })
  createdAt!: Date;
}

/**
 * One row of GET /api/auth/managers (Owner-only). `implements ManagerListRow`
 * for the same drift-protection as above. There is no password/passcode field —
 * `pendingInvite` is the only account-state signal, derived from
 * `password_hash IS NULL`; the hash never leaves the database.
 */
export class ManagerListRowDto implements ManagerListRow {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ example: 'Morgan Manager' })
  name!: string;

  @ApiProperty({ format: 'email', example: 'morgan@acme.test' })
  email!: string;

  @ApiProperty({ enum: ['active', 'inactive'], example: 'active' })
  status!: 'active' | 'inactive';

  @ApiProperty({
    description: 'Provisioned but not yet activated — no password set.',
    example: false,
  })
  pendingInvite!: boolean;

  @ApiProperty({
    type: String,
    format: 'uuid',
    nullable: true,
    description: "The manager's active team, or null if they have not created one.",
    example: null,
  })
  teamId!: string | null;

  @ApiProperty({ type: String, nullable: true, example: null })
  teamName!: string | null;

  @ApiProperty({ format: 'date-time', example: '2026-08-08T12:34:56.789Z' })
  createdAt!: Date;
}

/**
 * One row of GET /api/auth/teams/:id/members. `implements MemberRow` for the
 * same drift-protection as the others. The roster is members-only (the service
 * filters `role = 'member'`), so `role` documents as the single value 'member'
 * even though the column's TS type is the full UserRole union. Exactly the eight
 * fields decision #4 fixes — no hash, no passcode, no ranking/title/step.
 */
export class MemberRowDto implements MemberRow {
  @ApiProperty({ format: 'uuid', example: UUID_EXAMPLE })
  id!: string;

  @ApiProperty({ example: 'Sam Member' })
  name!: string;

  @ApiProperty({ format: 'email', example: 'sam@acme.test' })
  email!: string;

  @ApiProperty({
    enum: ['member'],
    example: 'member',
    description: 'Always "member" — the manager is not a roster row.',
  })
  role!: UserRole;

  @ApiProperty({ enum: ['active', 'inactive'], example: 'active' })
  status!: 'active' | 'inactive';

  @ApiProperty({
    description: 'Provisioned but not yet activated — no password set.',
    example: false,
  })
  pendingInvite!: boolean;

  @ApiProperty({
    format: 'uuid',
    description: 'The team this member belongs to — always the :id in the path.',
    example: UUID_EXAMPLE,
  })
  teamId!: string;

  @ApiProperty({ format: 'date-time', example: '2026-08-08T12:34:56.789Z' })
  createdAt!: Date;
}

